<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        Robô - DSIN
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- CSS Files -->
    <link href="assets/css/material-dashboard.css?v=2.1.1" rel="stylesheet" />
</head>

<body class="off-canvas-sidebar">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top text-white">
    <div class="container">
        <div class="navbar-wrapper">
            <a class="navbar-brand" href="#"></a>
        </div>
    </div>
</nav>
<!-- End Navbar -->
<div class="wrapper wrapper-full-page">
    <div class="page-header login-page header-filter" filter-color="red" style="background-image: url('assets/img/journey-login-background.png'); background-size: cover; background-position: top center;">
        <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
                    <form class="form" id="LoginValidation" method="" action="">
                        <div class="card card-login card-hidden">
                            <div class="card-header card-header-danger text-center">
                                <span><i class="fas fa-robot" style="font-size: 5vw;"></i></span>
                                <hr />
                                <h4 class="card-title">Login</h4>
                            </div>
                            <div class="card-body ">
                                <span class="bmd-form-group">
                                    <div class="input-group">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">
                                          <i class="material-icons">face</i>
                                        </span>
                                      </div>
                                      <input type="text" class="form-control" name="usuario" id="usuario" placeholder="Usuário" required="true" aria-required="true" aria-invalid="true">
                                    </div>
                                </span>
                                <span class="bmd-form-group">
                                    <div class="input-group">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">
                                          <i class="material-icons">lock_outline</i>
                                        </span>
                                      </div>
                                      <input type="password" class="form-control" name="senha" id="senha" placeholder="Senha" required="true" aria-required="true" aria-invalid="true">
                                    </div>
                                </span>
                            </div>

                            <div class="card-footer ml-auto mr-auto">
                                <button class="btn btn-danger" id="login">Entrar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <footer class="footer">
            <div class="container">
                <div class="copyright float-right">
                    <script>
                        document.write(new Date().getFullYear())
                    </script> DSIN - Desenvolvimento e Soluções em Informática.
                </div>
            </div>
        </footer>
    </div>
</div>
<!--   Core JS Files   -->
<script src="assets/js/core/jquery.min.js"></script>
<script src="assets/js/core/popper.min.js"></script>
<script src="assets/js/core/bootstrap-material-design.min.js"></script>
<script src="assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<script src="assets/js/plugins/sweetalert2.js"></script>
<!-- Forms Validations Plugin -->
<script src="assets/js/plugins/jquery.validate.min.js"></script>
<script>
    $(document).ready(function() {
        $().ready(function() {

            function setFormValidation(id) {
                $(id).validate({
                    messages: {
                        usuario: "Nome de Usuário obrigatório",
                        senha: "Digite a sua senha"
                    },
                    highlight: function(element) {
                        $(element).closest('.input-group').removeClass('has-success').addClass('has-danger');
                        $(element).closest('.form-check').removeClass('has-success').addClass('has-danger');
                    },
                    success: function(element) {
                        $(element).closest('.input-group').removeClass('has-danger').addClass('has-success');
                        $(element).closest('.form-check').removeClass('has-danger').addClass('has-success');
                    },
                    errorPlacement: function(error, element) {console.log(error);
                        $(element).closest('.bmd-form-group').append(error);
                    }
                });
            }


            $("#login").click(function() {
                setFormValidation('#LoginValidation');

                $("#login").submit();
            })
        });
    });
</script>
</body>